import type { MissionMode, MissionModeId, SampleImage } from '@/types';

export const MISSION_MODES: MissionMode[] = [
  {
    id: 'army',
    label: 'Army',
    shortLabel: 'ARMY',
    icon: 'Shield',
    tagline: 'UAV / Vehicle Surveillance',
    description: 'Ground reconnaissance & border patrol',
    useCase:
      'Edge-deployed AI on UAVs and vehicle-mounted cameras at forward operating bases. Filters obscured imagery from fog, dust, or smoke, keeping only tactically useful frames.',
    scenario:
      'A forward operating base receives a live UAV video feed over rugged terrain. Thick morning fog covers 60% of the patrol zone. The neuromorphic chip on-board the UAV discards fog-obscured frames and only transmits clear tactical views — saving bandwidth and power in a disconnected combat zone.',
    accent: 'amber',
    cloudThreshold: 35,
    context: 'Terrain / Ground',
    sensorLabel: 'UAV / Vehicle Camera',
    sensorIcon: 'Video',
    transmissionLabel: 'Tactical Downlink',
    transmissionIcon: 'Radio',
    metrics: [
      { label: 'Target Power', value: '20', unit: 'mW/image' },
      { label: 'Decision Latency', value: '<50', unit: 'ms' },
      { label: 'Bandwidth Saved', value: '~55', unit: '%' },
    ],
    palette: {
      baseHue: 30,
      baseSat: 25,
      baseLight: 35,
      cloudHue: 35,
      cloudSat: 8,
      cloudLight: 65,
      terrainHue: 25,
      terrainSat: 30,
      terrainLight: 30,
      cloudProbability: 0.45,
      gridColor: 'rgba(251, 191, 36, 0.08)',
    },
  },
  {
    id: 'navy',
    label: 'Navy',
    shortLabel: 'NAVY',
    icon: 'Anchor',
    tagline: 'Maritime Monitoring',
    description: 'Maritime surveillance & ship detection',
    useCase:
      'Identify vessels, monitor sea lanes, and detect anomalies across vast ocean areas with minimal power. Filters out open-water frames with no vessel activity.',
    scenario:
      'A maritime patrol drone monitors 200 nautical miles of coastline. Most frames show empty ocean with glare and haze. The neuromorphic chip filters out featureless sea-surface images and only downlinks frames with potential vessel signatures — extending mission endurance from hours to days.',
    accent: 'cyan',
    cloudThreshold: 40,
    context: 'Ocean / Coastal',
    sensorLabel: 'Maritime EO/IR Sensor',
    sensorIcon: 'Waves',
    transmissionLabel: 'Fleet Data Link',
    transmissionIcon: 'Radio',
    metrics: [
      { label: 'Target Power', value: '20', unit: 'mW/image' },
      { label: 'Decision Latency', value: '<50', unit: 'ms' },
      { label: 'Bandwidth Saved', value: '~60', unit: '%' },
    ],
    palette: {
      baseHue: 210,
      baseSat: 40,
      baseLight: 30,
      cloudHue: 200,
      cloudSat: 5,
      cloudLight: 70,
      terrainHue: 195,
      terrainSat: 50,
      terrainLight: 25,
      cloudProbability: 0.50,
      gridColor: 'rgba(34, 211, 238, 0.08)',
    },
  },
  {
    id: 'airforce',
    label: 'Air Force',
    shortLabel: 'AIR',
    icon: 'Plane',
    tagline: 'UAV / Aerial Reconnaissance',
    description: 'Aerial reconnaissance & airspace monitoring',
    useCase:
      'Filter high-altitude imagery for cloud-free tactical views. Prioritize clear-sky captures and discard images obscured by cloud cover during reconnaissance sorties.',
    scenario:
      'A high-altitude reconnaissance UAV flies above cloud cover at 60,000 ft. Its downward-looking camera captures both clear tactical targets and thick stratus cloud. The neuromorphic chip identifies and discards cloud-obscured frames in real-time — the pilot receives only actionable intelligence.',
    accent: 'sky',
    cloudThreshold: 25,
    context: 'High Altitude / Sky',
    sensorLabel: 'Aerial Recon Camera',
    sensorIcon: 'Camera',
    transmissionLabel: 'SATCOM Downlink',
    transmissionIcon: 'Satellite',
    metrics: [
      { label: 'Target Power', value: '20', unit: 'mW/image' },
      { label: 'Decision Latency', value: '<50', unit: 'ms' },
      { label: 'Bandwidth Saved', value: '~70', unit: '%' },
    ],
    palette: {
      baseHue: 200,
      baseSat: 30,
      baseLight: 45,
      cloudHue: 210,
      cloudSat: 5,
      cloudLight: 75,
      terrainHue: 190,
      terrainSat: 25,
      terrainLight: 35,
      cloudProbability: 0.60,
      gridColor: 'rgba(56, 189, 248, 0.08)',
    },
  },
  {
    id: 'satellite',
    label: 'Satellite',
    shortLabel: 'SAT',
    icon: 'Satellite',
    tagline: 'Cloud-Covered Image Filtering',
    description: 'Orbital earth observation',
    useCase:
      'Onboard filtering of earth-observation imagery before downlink to ground stations. Discards cloud-covered images to save bandwidth, storage, and power.',
    scenario:
      'An earth-observation satellite captures 120 images per orbit at 8 MB each. Roughly 55% are covered by clouds and useless to ground stations. The neuromorphic chip analyzes each image on-orbit and discards cloud-covered frames — only useful imagery is downlinked, reducing bandwidth by up to 80%.',
    accent: 'teal',
    cloudThreshold: 50,
    context: 'Orbital / Earth',
    sensorLabel: 'Orbital Sensor',
    sensorIcon: 'Satellite',
    transmissionLabel: 'Ground Station Downlink',
    transmissionIcon: 'Radio',
    metrics: [
      { label: 'Target Power', value: '20', unit: 'mW/image' },
      { label: 'Decision Latency', value: '<50', unit: 'ms' },
      { label: 'Bandwidth Saved', value: '~80', unit: '%' },
    ],
    palette: {
      baseHue: 160,
      baseSat: 35,
      baseLight: 30,
      cloudHue: 200,
      cloudSat: 5,
      cloudLight: 72,
      terrainHue: 140,
      terrainSat: 40,
      terrainLight: 28,
      cloudProbability: 0.55,
      gridColor: 'rgba(45, 212, 191, 0.08)',
    },
  },
  {
    id: 'rural',
    label: 'Rural',
    shortLabel: 'RURAL',
    icon: 'Wheat',
    tagline: 'Low-Power Farm / Camera Edge AI',
    description: 'Precision agriculture & crop monitoring',
    useCase:
      'Monitor crop health, detect water stress, and filter cloudy captures in rural districts. Solar-powered edge cameras with neuromorphic chips run for months on a single charge.',
    scenario:
      'A network of solar-powered farm cameras monitors 500 acres of crops. Each camera captures an image every 30 minutes, but many are obscured by morning mist or cloud shadows. The neuromorphic chip filters out unusable frames locally — only clear crop images are sent over a low-bandwidth rural radio link.',
    accent: 'green',
    cloudThreshold: 45,
    context: 'Agriculture / Rural',
    sensorLabel: 'Farm Edge Camera',
    sensorIcon: 'Camera',
    transmissionLabel: 'Low-Bandwidth Radio',
    transmissionIcon: 'Wifi',
    metrics: [
      { label: 'Target Power', value: '20', unit: 'mW/image' },
      { label: 'Decision Latency', value: '<50', unit: 'ms' },
      { label: 'Bandwidth Saved', value: '~50', unit: '%' },
    ],
    palette: {
      baseHue: 90,
      baseSat: 45,
      baseLight: 35,
      cloudHue: 80,
      cloudSat: 5,
      cloudLight: 68,
      terrainHue: 70,
      terrainSat: 50,
      terrainLight: 30,
      cloudProbability: 0.40,
      gridColor: 'rgba(74, 222, 128, 0.08)',
    },
  },
  {
    id: 'disaster',
    label: 'Disaster',
    shortLabel: 'DIS',
    icon: 'Siren',
    tagline: 'Drone Imagery Under Limited Connectivity',
    description: 'Emergency response & damage assessment',
    useCase:
      'Rapid filtering for cloud-free disaster imagery. Drones in disaster zones with limited connectivity use on-board AI to prioritize usable captures for responders.',
    scenario:
      'A disaster-response drone surveys a flood zone with intermittent connectivity. Clouds and rain obscure much of the terrain. The neuromorphic chip filters out cloud-covered frames on-board — only clear damage-assessment imagery is queued for downlink when the drone briefly reconnects to the emergency network.',
    accent: 'rose',
    cloudThreshold: 30,
    context: 'Disaster Zone',
    sensorLabel: 'Drone Camera',
    sensorIcon: 'Camera',
    transmissionLabel: 'Emergency Network',
    transmissionIcon: 'Radio',
    metrics: [
      { label: 'Target Power', value: '20', unit: 'mW/image' },
      { label: 'Decision Latency', value: '<50', unit: 'ms' },
      { label: 'Bandwidth Saved', value: '~65', unit: '%' },
    ],
    palette: {
      baseHue: 0,
      baseSat: 30,
      baseLight: 30,
      cloudHue: 10,
      cloudSat: 5,
      cloudLight: 60,
      terrainHue: 350,
      terrainSat: 35,
      terrainLight: 25,
      cloudProbability: 0.55,
      gridColor: 'rgba(251, 113, 133, 0.08)',
    },
  },
];

export function getMissionMode(id: MissionModeId): MissionMode {
  return MISSION_MODES.find((m) => m.id === id) ?? MISSION_MODES[3];
}

export const SAMPLE_IMAGES: SampleImage[] = [
  {
    id: 'sat-earth-1',
    label: 'Earth from Orbit',
    url: 'https://images.pexels.com/photos/586056/pexels-photo-586056.jpeg?auto=compress&cs=tinysrgb&w=600',
    context: 'Orbital view with cloud formations',
  },
  {
    id: 'sat-earth-2',
    label: 'Blue Ocean',
    url: 'https://images.pexels.com/photos/30596893/pexels-photo-30596893.png?auto=compress&cs=tinysrgb&w=600',
    context: 'Clear ocean and continents',
  },
  {
    id: 'cloud-heavy',
    label: 'Dense Cloud Cover',
    url: 'https://images.pexels.com/photos/15421147/pexels-photo-15421147.png?auto=compress&cs=tinysrgb&w=600',
    context: 'Heavy cloud coverage',
  },
  {
    id: 'cloud-light',
    label: 'Scattered Clouds',
    url: 'https://images.pexels.com/photos/38351370/pexels-photo-38351370.jpeg?auto=compress&cs=tinysrgb&w=600',
    context: 'Clouds over green landscape',
  },
  {
    id: 'farmland-1',
    label: 'Agricultural Fields',
    url: 'https://images.pexels.com/photos/13544674/pexels-photo-13544674.jpeg?auto=compress&cs=tinysrgb&w=600',
    context: 'Clear farmland — usable',
  },
  {
    id: 'farmland-2',
    label: 'Crop Circle',
    url: 'https://images.pexels.com/photos/17685268/pexels-photo-17685268.jpeg?auto=compress&cs=tinysrgb&w=600',
    context: 'Irrigated crop field',
  },
  {
    id: 'flood-1',
    label: 'Flooded Area',
    url: 'https://images.pexels.com/photos/14823612/pexels-photo-14823612.jpeg?auto=compress&cs=tinysrgb&w=600',
    context: 'Disaster zone — flood',
  },
  {
    id: 'flood-2',
    label: 'Urban Flooding',
    url: 'https://images.pexels.com/photos/33779919/pexels-photo-33779919.jpeg?auto=compress&cs=tinysrgb&w=600',
    context: 'Kashmir flood — aerial',
  },
];
